### ISSUE TITLE
Run as pi user and not root

### ISSUE THREAD

**Issue by breedx2** [futel/audiofone#10]
There are some assumptions in the deployments now that assume we run as root...which is probably not desirable. Can we ensure that all files are copied over (ansible) as the pi user, and that everything works as the pi user?

Maybe this makes auto start more difficult and we can punt on doing this.

**Comment by kra** [comment]
For file ownership and permissions the way I do this in ansible is to change the permissions after it has been copied. See the futel-installation playbooks for examples.

For the user which is running programs, supervisord handles this. Again see the futel-nstallation playbooks.

If it's not efficient for you to do learn and do this now, add explicit comments to this issue or create new specific issues, which describe exactly what files (or complete directory trees) should have what ownership, and what program should be run by what users, and we can divvy up making the changes.

-------- Original Message --------

**Comment by breedx2** [comment]
Pretty sure the apps (audiofone.py and pd) were both already running as the pi user, but #29 ensured that the perms on audio and pd dirs were also pi.  We're good.
