### ISSUE TITLE
run-pd.sh missing

### ISSUE THREAD

**Issue by kra** [futel/audiofone#13]
TASK [make pd start script runnable] **********************************************
fatal: [pibox]: FAILED! => {"changed": false, "msg": "file (/opt/futel/src/pd/run-pd.sh) is absent, cannot continue", "path": "/opt/futel/src/pd/run-pd.sh", "state": "absent"}

**Comment by breedx2** [comment]
whoops!  I'll add it.

It _could_ be omitted from ansible, because supervisor runs pd directly withtout the script...but it wouldn't hurt to have it.

**Comment by breedx2** [comment]
actually, I already removed it from the repo and just forgot to remove it from ansible....so I won't add it, just remove from ansible.
