### ISSUE TITLE
Set up main py script in supervisord

### ISSUE THREAD

**Issue by breedx2** [futel/audiofone#25]
It needs to run on reboot.

**Comment by kra** [comment]
is the "main py script" audiofone.py?
does this do it when supervisord is running eg after a build https://github.com/futel/audiofone/blob/main/src/etc/supervisor/conf.d/audiofone.conf
is the issue that it does not get run after a reboot for whatever reason?

**Comment by kra** [comment]
audiofone.py runs after build and after reboot

**Comment by breedx2** [comment]
yeah that's all it was.  I had just missed that this was added and didn't want to lose track.  Thanks.
