### ISSUE TITLE
Create alsa config that gets restored on restart

### ISSUE THREAD

**Issue by breedx2** [futel/audiofone#27]
Mostly this should be for controlling default volume level.

I have confirmed that a modern distro like ours has systemd services:
* /usr/lib/systemd/system/sound.target.wants/alsa-state.service
* /usr/lib/systemd/system/sound.target.wants/alsa-restore.service
and there is a file here `/var/lib/alsa/asound.state` that contains the stored volume. 

Copying that file over should be enough, but some attention to volume might be needed.  I'm guessing that just setting the volume, rebooting, and then grabbing the saved/updated contents is enough.

**Comment by kra** [comment]
Last time I used a manual alsamixer step in the deploy, I also left notes about using amixer in a shell script for a more automated setup. Note that I did not really know what I was doing. In any case, when only shipping two units, a manual step in the deploy is ugly but workable if we don't manage to find a better solution, so long as it is described well enough in the readme (better than I described it at least)

https://github.com/kra/community-audio/blob/master/README

**Comment by kra** [comment]
Is this important? What is the behavior that we are seeing now and what would this solve?

Current usage is after the device has been rebooted, of course.

**Comment by breedx2** [comment]
The idea was to be able to automate the setting of the volume to our liking with any given ansible redeploy, and to have consistency.  Because the two phones didn't sound the same (different hardware), I manually set the volume and rebooted to confirm that it keeps between reboots.  It'll need to be manually reset if we do a full sd-card rebuild....but for now I think it's fine and we don't need this.

Feel free to reopen if this becomes important.
