### ISSUE TITLE
cannot play arbitrary wav files

### ISSUE THREAD

**Issue by kra** [futel/audiofone#32]
7592868_margarets_monologue.wav
plays as expected

1337_welcome.wav  468_dialtone.wav  666_bell.wav  
plays only silence

[foo.zip](https://github.com/futel/audiofone/files/6120551/foo.zip)

**Comment by kra** [comment]
on current main drop those wav files into src/opt/futel/src/audio, then dial prefix from dialtone

**Comment by breedx2** [comment]
If the requirement is to be able to play any old arbitrary wav file, then we will need to transcode on the fly because Pd needs a known format.  I can build a process that watches a dir and transcodes on the fly using ffmpeg or sox or something...or did you have something else in mind?
