### ISSUE TITLE
consider and possibly fix dialplan invalid behavior

### ISSUE THREAD

**Issue by kra** [futel/audiofone#33]
currently we notify user with fast busy as soon as the number is no longer valid. This is because we don't know how long the numbers are. I kept it this way because it helps the user.

Could instead notify user when number is invalid and is as long as the shortest valid number.

**Comment by breedx2** [comment]
Agreed that we don't need this for now.  

The behavior is nonstandard -- and I've never used a telephone that behaved this way...but for the project I agree that having an earlier indicator is probably helpful.  If there are more/future deploys, I could see revisiting this and possibly making this configurable.
