### ISSUE TITLE
sshpass should not be required

### ISSUE THREAD

**Issue by kra** [futel/audiofone#4]
README.md says sshpass is needed to avoid warnings, but this isn't the case on my box. The ssh user and pass are in the hosts file. This is OK because there will be no network and no expectation of protection during terminal access.

this is a minor issue, it's just a line in the README that would tax newbs

**Comment by breedx2** [comment]
It's on the devbox ansible side. I'll repro and post better output to justify it.

**Comment by kra** [comment]
this is now on a nonessential readme so no longer important
