### ISSUE TITLE
README leaves wifi active

### ISSUE THREAD

**Issue by kra** [futel/audiofone#5]
```
* pi network enabled and active
 * on the pi3, run raspi-config and enable+config wifi
```

We do not want any network access to the box after deployment. For example, we don't want drive by hax0rz to grief us.

This is a very minor issue especially if the box doesn't connect to an access point.

**Comment by breedx2** [comment]
Sure. We need to align if the instructions are for dev or deployment. I assumed there would be some final step to completely disable all networking (security and boot time)

**Comment by breedx2** [comment]
The web says that you can add these to the `[all]` section of `/boot/config.txt` to disable wifi:

* `dtoverlay=disable-wifi`
* `dtoverlay=disable-bt`

We should have this as a final deployment step.

**Comment by breedx2** [comment]
Manually disabled on both devices and confirmed that this does actually disable wifi.
